# Fly.io Configuration for ToT Print Farm System - TESTING ENVIRONMENT
# See https://fly.io/docs/reference/configuration/ for full reference

app = 'tot-printfarm-test'
primary_region = 'ams' # Amsterdam - closest to Sweden

# Automatically stop app when there are no requests (optional, remove if you want 24/7 uptime)
# auto_stop_machines = 'suspend'
# auto_start_machines = true
# min_machines_running = 0

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Persistent storage for database
# This ensures your database survives across deployments
[mounts]
  source = 'printfarm_data_test'
  destination = '/data'
  initial_size = '1gb'

# Environment variables
[env]
  NODE_ENV = 'testing'
  PORT = '3000'
  HOST = '0.0.0.0'

# Health checks to ensure the app is running properly
[checks]
  [checks.alive]
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
